### ISSUE TITLE
Add RSS feed on blog

### ISSUE THREAD

**Issue by e-krebs** [Polymer/polymer-project.org#9]
The title says it all: an RSS feed on the blog would allow many people to follow polymer's news much easier.

**Comment by koliyo** [comment]
Yes please! This makes following the blog impossible for me :/

**Comment by impressivewebs** [comment]
Just wanted to point out that the blog used to have an RSS feed at the following location:

http://blog.polymer-project.org/feed.xml

But for some reason this disappeared when the site started using:

https://www.polymer-project.org/blog/

as the blog URL. Maybe the feed is still there but this is just a matter of setting up a proper redirect from the previous RSS URL?
